In [ ]:
'''
Numpy is much faster than lists (default way for specifying matrices in python)
The reason is Numpy uses a fixed type to define values, which is a Int32 (4 bytes of 8 bits)
While lists are defined based on the following:
1. Size
2. Reference Count
3. Object Type
4. Object Value

As a result Numpy is faster because:
1. Faster to read less bytes of memory
2. When type checking when iterating over objects

Numpy is like MATLAB in python.

''' 

In [4]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(a)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Get dim and shape
a.ndim
a.shape

(3, 3)

In [8]:
# Get type
a.dtype

dtype('int32')

In [15]:
# Specify data type
a = np.array([1,2,3,4], dtype='int16')
a.itemsize # this gives the number of bytes

2

In [17]:
# Get total size, total number of items
a.size

4

In [20]:
a = np.zeros((3,3))+100
a = np.full((3,3), 100)
print(a)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [24]:
# random numbers
a = np.random.rand(4,2)
a = np.random.random_sample(a.shape)
print(a)

[[0.12049141 0.60833226]
 [0.44281601 0.77077678]
 [0.85238795 0.83614592]
 [0.06488407 0.55601908]]


In [41]:
# random ints
a = np.random.randint(10, 20+1, size=(3,2))
print(a)

[[19 18]
 [12 13]
 [11 13]]


In [43]:
a = np.identity(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [48]:
b = np.repeat(a, 3, axis=1)
print(b)

[[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]]


In [50]:
a = np.ones((5,5))
b = np.zeros((3,3)); b[1,1]=9
a[1:4, 1:4] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
# Cautious when copying arrays
a = np.ones((3,3))
b = a
a[2,2]=100
print(b)

# You have to use "copy()" instead of "="
a = np.ones((3,3))
b = a.copy()
a[2,2]=100
print(b)

[[  1.   1.   1.]
 [  1.   1.   1.]
 [  1.   1. 100.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [59]:
# Mathematics
a = np.random.rand(3,3)
b = np.ones(a.shape)
c = np.dot(a, b) # matrix multiplication
print(a)
print(c)

[[0.70216582 0.06967119 0.69618097]
 [0.19370256 0.41672036 0.94858703]
 [0.04532458 0.14935122 0.31143079]]
[[1.46801797 1.46801797 1.46801797]
 [1.55900995 1.55900995 1.55900995]
 [0.50610659 0.50610659 0.50610659]]


### Linear Algebra

In [65]:
a = np.full((2,3), 1)
print(a)
b = np.full((3,2), 2)
print(np.dot(b, a))
print(np.matmul(b, a))

[[1 1 1]
 [1 1 1]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [72]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)
eigenvalues, eigenvectors = np.linalg.eig(c)
print(eigenvalues)

[1. 1. 1.]


### Statistics

In [79]:
a = np.random.rand(3,3)
np.min(a)
np.std(a)
np.var(a)
np.sum(a, axis=0)

array([1.41744192, 1.40246628, 1.9146478 ])

### Rearranging matrices

In [83]:
a = np.random.rand(9, 1)
print(a)
a.reshape(3,3) # Important note: it is a row-major, filling along rows first

[[0.82154273]
 [0.76579845]
 [0.3776659 ]
 [0.30240606]
 [0.81036883]
 [0.50871102]
 [0.82929597]
 [0.54701696]
 [0.47193566]]


array([[0.82154273, 0.76579845, 0.3776659 ],
       [0.30240606, 0.81036883, 0.50871102],
       [0.82929597, 0.54701696, 0.47193566]])

### Vertical-Horizontal stacking of vectors or matrices

In [90]:
a = np.random.rand(3,2)
b = np.random.rand(3,2)
np.vstack([a, b])
#np.hstack([a, b])

array([[0.83340587, 0.93994217],
       [0.29369038, 0.00655715],
       [0.98938336, 0.44819947],
       [0.24282794, 0.67878584],
       [0.03437081, 0.29610494],
       [0.35468055, 0.63777486]])

### Load data from file

In [91]:
# The best approach is genfromtext
#data = np.genfromtext('data.text', delimiter=',')
#data.astype('int32')

### Boolean Masking and Advanced Indexing

In [107]:
a = np.random.randint(1,10,(3,3))
print(a)
idxs = np.where(a>5, a+10, a)
print(idxs)

np.any(a>50, axis=0)
np.all(a>5)

((a>1),(a<10))

a = np.identity(3)
a[0,1]=1
idxs = np.where(a==1)
print(idxs[0])
print(idxs[1])


[[9 8 9]
 [1 9 7]
 [5 2 1]]
[[19 18 19]
 [ 1 19 17]
 [ 5  2  1]]
[0 0 1 2]
[0 1 1 2]
