### Array vs List

In [2]:
import numpy as np

In [17]:
a = np.array([1,2,3])
l = [1,2,3]
print(a,l)

# First differencce: numpy does not support append() as in lists
#a.append(4) # does not work
l.append(4)

# Second difference: broacasting is different
a = a + 1 # this is a matrix operation
l = l + [1] # this is a list operation

print(a, l)


a = np.array([1,2,3])
l = [1,2,3]
a = a * 2 # this is a matrix operation
l = l * 2 # this is a list operation

print(a, l)

a = np.array([1,2,3])
l = [1,2,3]
a = np.sqrt(a) # this is a matrix operation

print(a)



# dot product
l1 = [1,2,3]
l2 = [1,2,3]
a = np.array([1,2,3])
print(np.dot(a,a))

print(a @ a) # same as np.dot
print(a * a) # element-wise product


[1 2 3] [1, 2, 3]
[2 3 4] [1, 2, 3, 4, 1]
[2 4 6] [1, 2, 3, 1, 2, 3]
[1.         1.41421356 1.73205081]
14
14
[1 4 9]


### Speed test between np.array and list

In [26]:
from timeit import default_timer as timer
n = 1000
a = np.random.randn(n)
b = np.random.randn(n)

A = list(a)
B = list(b)

T = len(a)

def dot1():
    dot = 0
    for i in range(T):
        dot += A[i]*B[i]
    return dot

def dot2():
    return np.dot(a, b)

start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end - start


start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end - start



In [27]:
print(t1/t2)

143.1388218991457


### Multidimensional Arrays

In [30]:
a = np.zeros((2))
a.shape
a = np.zeros((2,2))
a.shape
a = np.zeros((2,2,2))
a.shape
a = np.zeros((2,2,2,2))
a.shape
a = np.zeros((2,2,2,2,2))
a.shape

(2, 2, 2, 2, 2)

### Matrix inversion

In [59]:
a = np.identity(10)
np.linalg.inv(a)
np.diag(a)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
a = np.random.randint(1, 10, (3,3))
print(a)
idxs = np.argwhere(a>5)
print(idxs)
#print(a[idxs])

[[4 2 2]
 [3 1 7]
 [9 2 4]]
[[1 2]
 [2 0]]


### Append in Numpy arrays

In [79]:
a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,2))
c = np.concatenate((a,b), axis=0) # same thing as in vstack and hstack
c1 = np.vstack((a,b))
print(a)
print(b)
print(c)
print(c1)
c.shape

[[1 8]
 [2 8]]
[[9 4]
 [6 2]]
[[1 8]
 [2 8]
 [9 4]
 [6 2]]
[[1 8]
 [2 8]
 [9 4]
 [6 2]]


(4, 2)

### Broadcasting

In [81]:
a = np.array([1,0,1])
b = np.random.randint(1,10,(2,3)) # the sizes do not match for matrix sum, but numpy does it anyways through Broadcasting.
print(a)
print(b)
print(a +b)

[1 0 1]
[[4 6 8]
 [2 5 4]]
[[5 6 9]
 [3 5 5]]


In [90]:
a = np.arange(20)
print(a)


a = np.linspace(0, 10, 5)
print(a)

a = np.random.choice(10, size = 5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.   2.5  5.   7.5 10. ]
[0 6 8 7 2]


In [97]:
a = np.random.choice([1,2,3,4,5], 10, p=[0.1, 0.1, 0.1, 0.6, 0.1])
print(a)

[2 4 5 4 3 4 1 4 3 4]


### Linear Algebra

In [119]:
a = np.array([[1,2],[3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
#print(eigenvalues)
# To verify the results of the eigendecomposition, use the following:
# e_vec * e_val = A * e_vec
#print(eigenvectors[:,0] * eigenvalues[0]) 
#print(a @ eigenvectors[:,0])

# Or the following:
#   a = Q * diag(eigenvalues) * Q.inv
Q = eigenvectors.copy()
print(np.dot( np.dot(Q,np.diag(eigenvalues)) , np.linalg.inv(Q)) )
print(a)

[[1. 2.]
 [3. 4.]]
[[1 2]
 [3 4]]


### Solving Linear Systems
Q: The addmission fee at a small fair is \\$1.50 for children and \\$4.0 for adults. On a certain day, 2200 people enter the fair and \\$5050 is collected. How many children and how many adults attended the fair?

$$ x_1 + x_2 = 2200$$
$$ 1.5x_1 + 4x_2 = 5050$$

In [125]:
# 1. Manual Approach:
A = np.array([[1,1],[1.5,4.0]])
b = np.array([2200, 5050])
x = np.dot(np.linalg.inv(A) , b) # equivalent to np.linalg.inv(A).dot(b)
print(x)

# 2. Better approach without computing the inverse (numerical issues)
x = np.linalg.solve(A, b)
print(x)

[1500.  700.]
[1500.  700.]
